/**
 * 2026-08-25 — Apple Watch target (SmartPlay Caddie).
 *
 * Tim: "having yardage on a watch is, like, a minimum for most golf guys and most golf apps."
 * Wear OS has shipped this since July; this is the Apple half.
 *
 * Generated by @bacons/apple-targets so the watch app lives here rather than inside a checked-in
 * ios/ directory — this project is Continuous Native Generation (no ios/ or android/ in the repo),
 * so anything that must survive a prebuild has to be expressed as config + sources like this.
 *
 * ⚠️ KNOWN TOOLING BUG — EvanBacon/expo-apple-targets#175 (opened 2026-02-18, still open) reports
 * that `expo prebuild` emits incorrect watch wiring: wrong target dependencies, a MISSING
 * "Embed Watch Content" copy phase, and duplicate or stale watch.app entries. A build can therefore
 * succeed and produce an app with NO watch app embedded.
 *
 * ✅ CHECKED 2026-08-30 against a real prebuild of THIS project, rather than assumed either way.
 * The wiring is correct here: the Embed Watch Content phase exists, is a PBXCopyFilesBuildPhase
 * with dstPath "$(CONTENTS_FOLDER_PATH)/Watch" and dstSubfolderSpec 16, contains the watch app
 * product, and is attached to the app target's buildPhases alongside a real target dependency.
 * Re-check if apple-targets is upgraded. Still worth confirming the built .ipa contains Watch/*.app
 * the first time one is produced.
 *
 * ⚠️ WHAT DID BITE US — SIGNING, not embedding. Build 13 (2026-08-30) failed in "Run fastlane":
 * "No profiles for 'com.smartplaycaddie.app.watchkitapp' were found ... Automatic signing is
 * disabled and unable to generate a profile." apple-targets hardcodes CODE_SIGN_STYLE "Automatic"
 * for watch targets, EAS turns automatic signing off for store builds, and the target was left with
 * no profile and no way to make one. Three config-plugin approaches could not reach it: the package
 * installs its OWN base mod (withXcodeProjectBetaBaseMod) and writes the target in a phase nothing
 * registered in app.json can follow. Fixed with `patches/@bacons+apple-targets+5.0.0.patch`, which
 * flips that one function to "Manual" so EAS's injected profile is honoured. `postinstall:
 * patch-package` applies it on EAS too.
 */
module.exports = {
  type: 'watch',
  /**
   * 2026-08-30 — `name` IS THE XCODE TARGET NAME, and it must not collide with the app's.
   *
   * Build 15 failed with the profiles crossed: the main app got the WATCH profile and the watch got
   * none. EAS keys credentials by target NAME and printed both of ours identically:
   *
   *     - Target: SmartPlayCaddie   Bundle Identifier: com.smartplaycaddie.app
   *     - Target: SmartPlayCaddie   Bundle Identifier: com.smartplaycaddie.app.watchkitapp
   *
   * "SmartPlay Caddie" and "SmartPlayCaddie" are the same string once the space is normalised away,
   * so the second entry overwrote the first and both targets drew from one bucket.
   *
   * `displayName` is what a player actually reads on the watch (it sets
   * INFOPLIST_KEY_CFBundleDisplayName); `name` only names the target. Splitting them keeps the watch
   * app called "SmartPlay Caddie" while giving EAS two names it can tell apart.
   */
  name: 'SmartPlayWatch',
  displayName: 'SmartPlay Caddie',
  bundleIdentifier: 'com.smartplaycaddie.app.watchkitapp',
  deploymentTarget: '9.0',
  /**
   * 2026-08-30 — REQUIRED. Build 17 uploaded successfully and Apple REJECTED it in processing:
   *
   *   Missing Info.plist value. A value for the Info.plist key 'CFBundleIconName' is missing in the
   *   bundle 'com.smartplaycaddie.app.watchkitapp'. (90713)
   *   Missing Icons. No icons found for watch application 'SmartPlayWatch.app'. (90391)
   *
   * The watch target's asset catalog held only `$accent.colorset` — no AppIcon at all. apple-targets
   * sets ASSETCATALOG_COMPILER_APPICON_NAME only when an `icon` is supplied ("Only set AppIcon when
   * an icon is provided, otherwise Xcode will fail to build because the asset catalog doesn't
   * exist"), so with no icon the watch app shipped iconless and Apple would not accept it.
   *
   * It has its own watch generator (generateWatchIconsInternalAsync) which produces the watchOS
   * sizes and flattens alpha — our source is 892×892 WITH an alpha channel, and Apple rejects icons
   * that keep one, so that flattening matters rather than being incidental.
   *
   * Note this failed at PROCESSING, not at build: xcodebuild was perfectly happy. No local compile
   * would have caught it — only an actual upload does.
   */
  icon: '../../assets/images/icon.png',
  colors: {
    // Canonical SmartPlay neon green, matching the Wear OS face and the app accent.
    $accent: '#88F700',
  },
};
