/**
 * 2026-08-25 — Apple Watch target (SmartPlay Caddie).
 *
 * Tim: "having yardage on a watch is, like, a minimum for most golf guys and most golf apps."
 * Wear OS has shipped this since July; this is the Apple half.
 *
 * Generated by @bacons/apple-targets so the watch app lives here rather than inside a checked-in
 * ios/ directory — this project is Continuous Native Generation (no ios/ or android/ in the repo),
 * so anything that must survive a prebuild has to be expressed as config + sources like this.
 *
 * ⚠️ KNOWN TOOLING BUG — read before building. EvanBacon/expo-apple-targets#175 (opened 2026-02-18,
 * still OPEN as of 2026-08-25) reports that `expo prebuild` emits incorrect watch wiring: wrong
 * target dependencies, a MISSING "Embed Watch Content" copy phase on the app target, and duplicate
 * or stale watch.app entries. A build can therefore succeed and produce an app with NO watch app
 * embedded. The documented workaround is a patch-package patch over the target-detection logic.
 * Verify the built .ipa actually contains Watch/*.app before assuming this shipped.
 */
module.exports = {
  type: 'watch',
  name: 'SmartPlay Caddie',
  bundleIdentifier: 'com.smartplaycaddie.app.watchkitapp',
  deploymentTarget: '9.0',
  colors: {
    // Canonical SmartPlay neon green, matching the Wear OS face and the app accent.
    $accent: '#88F700',
  },
};
