import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import { getPersistStorage } from '../services/ssrSafeStorage';

/**
 * Phase BR — Tutorial library + active practice context.
 *
 * Distinct from cageStore (which captures the player's own swings for
 * biomechanical analysis). This store captures *instructional* videos —
 * coaching content the player wants to learn from. Each entry is a
 * `TutorialEntry` with the teaching summary Sonnet extracted from the
 * player's notes + a representative frame.
 *
 * Active practice context: a subset of tutorial entries flagged as
 * `is_active`. These are injected into Kevin's system prompt during
 * round play so his caddie advice reflects what the player is currently
 * learning.
 *
 * Cap: at most MAX_ACTIVE active tutorials at any time. This keeps the
 * Kevin prompt bounded (token budget management — Component 13).
 *
 * Audio transcription pipeline is intentionally NOT here yet (BR scope
 * deferred to BR2). Today the teaching summary is generated by Sonnet
 * from the player's manually-entered title + key cues + 1 representative
 * video frame. When Whisper integration ships, the transcript becomes
 * the primary input and the structured summary auto-populates.
 */

import type { ClubId } from '../services/clubRecognition';

export type TutorialSource = 'uploaded_video' | 'youtube_link' | 'manual_note';

export interface TutorialEntry {
  id: string;
  /** When this entry was added to the library. */
  added_at: number;
  /** Where the source content lives. local URI for uploads; URL for youtube; null for note-only. */
  source_kind: TutorialSource;
  source_uri: string | null;

  /** Player-facing display title. Required. */
  title: string;
  /** Optional instructor name ("Marc Solomon", "unknown coach"). */
  instructor: string | null;
  /** Optional club codes the lesson targets (PW, GW, SW, LW, etc — match
   *  the ClubId catalog in services/clubRecognition.ts). */
  target_clubs: ClubId[];
  /** Optional player-typed notes — feeds into the Sonnet extraction. */
  player_notes: string | null;

  /** Sonnet-extracted teaching focus (one sentence). */
  teaching_focus: string;
  /** Sonnet-extracted key cues (3-5 short phrases the player should
   *  remember during the relevant shots). */
  key_cues: string[];
  /** Sonnet-extracted situational context — where this lesson applies
   *  ("approach shots inside 100 yards", "bunker shots", "wedges from
   *  the rough"). Optional. */
  target_situations: string[];
  /** Sonnet confidence in its extraction. */
  extraction_confidence: 'high' | 'medium' | 'low';

  /** Active practice context flag. When true, this tutorial is injected
   *  into Kevin's system prompt during rounds. Capped at 3 active. */
  is_active: boolean;
}

export const MAX_ACTIVE_TUTORIALS = 3;

interface TutorialState {
  tutorials: TutorialEntry[];

  // ─── ACTIONS ────────────────────────────────────────────────────────
  addTutorial: (
    entry: Omit<TutorialEntry, 'id' | 'added_at' | 'is_active'>
  ) => string;
  updateTutorial: (id: string, patch: Partial<TutorialEntry>) => void;
  deleteTutorial: (id: string) => void;
  /** Toggle is_active. Enforces MAX_ACTIVE cap — when activating beyond
   *  cap, returns false without changing state so caller can prompt. */
  setActive: (id: string, active: boolean) => boolean;
  /** Returns currently-active tutorials (sorted by most-recently-added). */
  getActive: () => TutorialEntry[];
}

export const useTutorialStore = create<TutorialState>()(
  persist(
    (set, get) => ({
      tutorials: [],

      addTutorial: (entry) => {
        const id = `${Date.now()}_tutorial`;
        const newEntry: TutorialEntry = {
          ...entry,
          id,
          added_at: Date.now(),
          is_active: false,
        };
        set(s => ({ tutorials: [newEntry, ...s.tutorials] }));
        return id;
      },

      updateTutorial: (id, patch) =>
        set(s => ({
          tutorials: s.tutorials.map(t =>
            t.id === id ? { ...t, ...patch, id: t.id, added_at: t.added_at } : t,
          ),
        })),

      deleteTutorial: (id) =>
        set(s => ({ tutorials: s.tutorials.filter(t => t.id !== id) })),

      setActive: (id, active) => {
        const current = get().tutorials;
        const target = current.find(t => t.id === id);
        if (!target) return false;
        if (active && target.is_active) return true;
        if (!active && !target.is_active) return true;

        if (active) {
          const activeCount = current.filter(t => t.is_active).length;
          if (activeCount >= MAX_ACTIVE_TUTORIALS) return false;
        }

        set({
          tutorials: current.map(t =>
            t.id === id ? { ...t, is_active: active } : t,
          ),
        });
        return true;
      },

      getActive: () => {
        return get().tutorials
          .filter(t => t.is_active)
          .sort((a, b) => b.added_at - a.added_at);
      },
    }),
    {
      name: 'tutorial-store-v1',
      storage: createJSONStorage(() => getPersistStorage()),
    },
  ),
);
