/**
 * EVERY MIC, ONE CADDIE.
 *
 * 2026-07-01 (mic convergence) — the universal badge / earbud / hands-free path
 * (services/listeningSession) reached a different brain from the caddie-tab mic. This file was
 * written to join them.
 *
 * 2026-08-23 (Tim, sprint finish — "a single source of truth, a single path, a total present
 * caddie… getting all the generics out, no robots, no built-for-failure paths") — it had not
 * finished the job. It joined the ROUTE and kept FOUR hand-built payloads alive behind it:
 *
 *   tryPipecat             → /api/pipecat-turn with the nested buildPipecatContext object
 *   tryKevin               → /api/kevin with ~25 hand-listed fields
 *   generateProactiveOpener→ /api/kevin with ~16 hand-listed fields
 *   (plus useKevin + useVoiceCaddie, already unified on 08-22)
 *
 * Read what that meant on the course. `tryKevin` is the EARBUD path: no course intelligence, no
 * hazards, no round stats, no bag, no handedness. And `generateProactiveOpener` is the caddie's
 * FIRST WORDS when the app opens — the moment that sets whether he sounds like your caddie or like
 * an app — assembled from sixteen fields. That is where "generic" came from. Not the model, not the
 * prompt: the payload.
 *
 * Both now go through services/caddieBrain.askCaddie → buildCaddieRequestBody → /api/kevin. One
 * payload, one brain, one conversation history.
 *
 * AND THE LADDER IS GONE. This used to try pipecat, then kevin, then hand back whatever it got, so
 * the player could receive any of three different caddies and had no way to tell which. A phone has
 * signal essentially all the time; the ladder was not buying reliability, it was buying an
 * inconsistent caddie. One real attempt, honestly reported.
 */

import { askCaddie } from './caddieBrain';
import { mayTalkToCaddie } from './featureAccess';
import { setPipecatHistory, clearPipecatHistory } from './voice/pipecatHistory';
import { useSettingsStore } from '../store/settingsStore';

export interface BrainReply {
  text: string | null;
  audioBase64: string | null;
  /** Normalized tool actions to dispatch (may be empty). */
  toolActions: unknown[];
  /** Which brain answered — telemetry / debugging. There is only one now. */
  source: 'kevin' | 'none';
}

const NO_ANSWER: BrainReply = { text: null, audioBase64: null, toolActions: [], source: 'none' };

export function clearConversationalHistory(): void { clearPipecatHistory(); }

/**
 * Route a conversational utterance to the caddie.
 *
 * The one chokepoint every hands-free utterance passes through, which is why the stuck-player
 * check lives here.
 */
export async function conversationalBrainTurn(utterance: string, opts?: { timeoutMs?: number }): Promise<BrainReply> {
  // 2026-08-25 — the one caddie access gate. NO_ANSWER is this module's own vocabulary for "the
  // brain did not answer", so every existing caller already handles it correctly.
  if (!mayTalkToCaddie()) return NO_ANSWER;
  const timeoutMs = opts?.timeoutMs ?? 15_000;
  // 2026-08-09 (dead-trigger audit) — the user_explicit_stuck team-intel trigger was built,
  // thresholded, given a full suggestion UI, and never called. Conservative phrase gate; the
  // store's per-session cap + pending guard bound it further.
  try {
    if (/(i'?m (so |really )?(stuck|frustrated)|not getting (any )?better|keep (doing|hitting) the same|what am i doing wrong)/i.test(utterance)) {
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const ti = require('./teamIntelligence') as typeof import('./teamIntelligence');
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const surf = (require('./activeSurfaceRegistry') as typeof import('./activeSurfaceRegistry')).getActiveSurface();
      // eslint-disable-next-line @typescript-eslint/no-require-imports
      const roundActive = (require('../store/roundStore') as typeof import('../store/roundStore')).useRoundStore.getState().isRoundActive;
      const pillar = roundActive ? 'round' as const
        : surf === 'cage' || surf === 'swing_library' || surf === 'swing_detail' ? 'cage' as const
        : surf === 'drill_detail' || surf === 'drill_session' ? 'drills' as const
        : 'play' as const;
      ti.evaluateUserExplicitStuck(pillar);
    }
  } catch { /* suggestion is best-effort — never blocks the turn */ }

  const turn = await askCaddie({
    message: utterance,
    language: useSettingsStore.getState().language ?? 'en',
    timeoutMs,
  });
  if (!turn) return NO_ANSWER;
  return { text: turn.text, audioBase64: turn.audioBase64, toolActions: turn.toolActions, source: 'kevin' };
}

/**
 * 2026-07-25 (Tim — KILL the canned opener) — the caddie's post-splash OPENER, generated by the
 * BRAIN instead of a bundled mp3. The mp3 had no text anywhere in the app, so the player's reply
 * ("yes") hit the brain with EMPTY history and got a generic "what do you want to work on?" — the
 * "simpleton, not AI" bug. This makes the opener a real, personalized line AND seeds the shared
 * conversation history with it, so the very next reply is answered in context.
 *
 * 2026-08-23 — and it now knows who it is greeting. It was built from sixteen hand-listed fields
 * while the full picture sat one function call away: this is the first thing the player hears, and
 * it was the thinnest payload in the app.
 *
 * Best-effort: text:null on any failure and the caller stays silent. There is no canned fallback —
 * a canned opener was the whole problem.
 */
export async function generateProactiveOpener(opts?: { timeoutMs?: number }): Promise<BrainReply> {
  const turn = await askCaddie({
    // A directive, NOT a player utterance — is_proactive tells the brain the player didn't ask.
    message: 'The player just opened the app and is on the caddie home screen (not in a round). Greet them as their caddie and open the conversation — warm, natural, one or two sentences, by name if you know it. If you know their game, you may nod to it. Never read a script.',
    language: useSettingsStore.getState().language ?? 'en',
    timeoutMs: opts?.timeoutMs ?? 12_000,
    overrides: { is_proactive: true, isRoundActive: false },
  });
  if (!turn?.text) return NO_ANSWER;
  /**
   * Seed the shared history with ONLY the caddie's opener (assistant turn). askCaddie appended the
   * DIRECTIVE as a user turn — replacing the history here drops it, which is deliberate: the player
   * never said that sentence, and leaving it in makes the caddie answer the instruction instead of
   * the person.
   */
  setPipecatHistory([{ role: 'assistant', content: turn.text }]);
  return { text: turn.text, audioBase64: turn.audioBase64, toolActions: turn.toolActions, source: 'kevin' };
}
