/**
 * 2026-05-26 — Fix DY: Personal Caddie recorded voice clips.
 *
 * Tim wants the personal-caddie persona to be able to use the user's
 * OWN voice for short fixed phrases (greetings + verbal reactions),
 * with OpenAI TTS as the fallback for anything outside this catalog
 * AND for live conversational responses (which can't be pre-recorded).
 *
 * Architecture:
 *   - Fixed catalog of phrases (below). Order = display order in UI.
 *   - Each phrase has a stable `id` so the recorded file is keyed by
 *     id, not by the (mutable) text. Renaming a phrase keeps the
 *     existing recording valid.
 *   - Lookup: normalizeForMatch(text) → canonical form → maps phrase
 *     id. voiceService.speak() checks this BEFORE calling /api/voice.
 *   - Files live in FileSystem.documentDirectory + 'customCaddieClips/'
 *     (NOT cache — these are user-created assets that survive eviction).
 *   - URIs persisted on playerProfileStore.customCaddieClips keyed by
 *     phrase id; the file itself is the source of truth, the URI is
 *     just a pointer.
 *
 * Not in v1 (deferred):
 *   - Cloud backup of clips (matches the device-local-only library
 *     situation tracked in [[cloud-backup-roadmap]]).
 *   - Free-form recording (record any phrase). Catalog-only keeps the
 *     lookup deterministic — no fuzzy matching, no surprise misfires.
 *   - Per-persona clips (currently scoped to Use My Custom Caddie ON).
 */

export interface CustomCaddiePhrase {
  /** Stable identifier — never rename. */
  id: string;
  /** What the user will hear / record. Exact text the caddie also speaks. */
  text: string;
  /** Short hint for the UI ("when the caddie greets you in the morning"). */
  hint: string;
  /** Display category — used for section grouping in the recorder UI. */
  category: 'greeting' | 'reaction' | 'encouragement' | 'closing';
}

// 2026-05-26 — Catalog kept deliberately short for v1. These are
// phrases the caddie says VERBATIM in code (not generated by an LLM),
// so a recording will always be triggered when the matching code path
// fires. Adding new ids is safe (will surface in the UI as un-recorded
// rows); renaming or removing ids will orphan existing recordings.
export const CUSTOM_CADDIE_PHRASES: CustomCaddiePhrase[] = [
  // Greetings — match getGreetingCaption() text variants.
  { id: 'greet_welcome_back',  text: "Welcome back. Let's play some golf.", hint: "Morning / midday return greeting", category: 'greeting' },
  { id: 'greet_late_round',    text: "Squeezing in a late round?",         hint: "Afternoon / evening greeting",         category: 'greeting' },
  { id: 'greet_good_morning',  text: "Good morning. Ready to play?",       hint: "Early morning greeting",                category: 'greeting' },
  { id: 'greet_good_evening',  text: "Good evening. Good to see you.",     hint: "After-work evening greeting",           category: 'greeting' },
  // Quick reactions — short verbal hits during play.
  { id: 'react_good_shot',     text: "Good shot.",                          hint: "Solid contact",                         category: 'reaction' },
  { id: 'react_nice_contact',  text: "Nice contact.",                       hint: "Clean strike",                          category: 'reaction' },
  { id: 'react_solid_putt',    text: "Solid putt.",                         hint: "Putt that holds the line",              category: 'reaction' },
  { id: 'react_good_drive',    text: "Good drive.",                         hint: "Solid tee shot",                        category: 'reaction' },
  { id: 'react_tough_break',   text: "Tough break.",                        hint: "Bad bounce / unlucky result",           category: 'reaction' },
  // Encouragement — confidence-building lines between shots.
  { id: 'encourage_stay',      text: "Stay with it.",                       hint: "Mid-round encouragement",               category: 'encouragement' },
  { id: 'encourage_reset',     text: "Let's reset.",                        hint: "After a bad hole — reset mindset",      category: 'encouragement' },
  { id: 'encourage_got_this',  text: "You got this.",                       hint: "Pressure shot",                         category: 'encouragement' },
  { id: 'encourage_easy',      text: "Nice and easy.",                      hint: "Slow the swing down",                   category: 'encouragement' },
  { id: 'encourage_take_time', text: "Take your time.",                     hint: "No rush — settle in",                   category: 'encouragement' },
  // Closing — round end / session end.
  { id: 'close_lets_go',       text: "Let's go.",                           hint: "Walking off the tee / next hole",       category: 'closing' },
  { id: 'close_nice_round',    text: "Nice round.",                         hint: "Round complete",                        category: 'closing' },
];

/**
 * Normalize a text string into a canonical form for clip matching.
 *
 * - lowercase
 * - trim
 * - strip trailing punctuation (".", "!", "?", ",") so "Good shot" and
 *   "Good shot." collide as the same recording
 * - collapse internal whitespace
 *
 * Intentionally NOT fuzzy — exact normalized match only. Fuzzy matching
 * would risk firing a recording on the wrong phrase (e.g., "Good drive
 * to the left" matching "Good drive."), which would feel like a bug.
 */
export function normalizeForMatch(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/[.!?,]+$/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Build a Map of normalized phrase text → phrase id for O(1) lookup.
 * Memoized at module level — the catalog is static.
 */
let _normalizedIndex: Map<string, string> | null = null;
function getNormalizedIndex(): Map<string, string> {
  if (_normalizedIndex) return _normalizedIndex;
  const m = new Map<string, string>();
  for (const p of CUSTOM_CADDIE_PHRASES) {
    m.set(normalizeForMatch(p.text), p.id);
  }
  _normalizedIndex = m;
  return m;
}

/**
 * Look up the recording URI for a given text, if the user has a clip
 * for the matching phrase. Returns null when:
 *   - text doesn't normalize to any catalog entry
 *   - user has no recording for the matched phrase id
 *   - clips map is missing / empty
 *
 * Caller (voiceService.speak) is responsible for the useCustomCaddie
 * gate — this helper does NOT consult settings.
 */
export function lookupClipUri(
  text: string,
  clips: Record<string, string> | null | undefined,
): string | null {
  if (!clips) return null;
  const norm = normalizeForMatch(text);
  const phraseId = getNormalizedIndex().get(norm);
  if (!phraseId) return null;
  const uri = clips[phraseId];
  return typeof uri === 'string' && uri.length > 0 ? uri : null;
}

/** Phrases grouped by category for UI rendering. */
export function phrasesByCategory(): Record<CustomCaddiePhrase['category'], CustomCaddiePhrase[]> {
  const out: Record<CustomCaddiePhrase['category'], CustomCaddiePhrase[]> = {
    greeting: [], reaction: [], encouragement: [], closing: [],
  };
  for (const p of CUSTOM_CADDIE_PHRASES) out[p.category].push(p);
  return out;
}
